#!/usr/bin/env python3
"""Generate a pyATS testbed from lab.env.

lab.env stays the single source of truth for the topology; this renders it into
the inventory format pyATS expects, so device facts live in one place instead of
being threaded through ~45 --variable arguments on the robot command line.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from provision import load_env, routers, spokes, static_pairs, dynamic_addresses, pool_bounds  # noqa: E402

LAB = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def render(env):
    lines = [
        "# Generated by tools/make_testbed.py from lab.env -- do not edit by hand.",
        "testbed:",
        "  name: c8000v-hub-and-spoke",
        "  credentials:",
        "    default:",
        f"      username: {env['VM_USER']}",
        f"      password: {env['VM_PASS']}",
        "    enable:",
        f"      password: {env['VM_PASS']}",
        "",
        "devices:",
    ]
    for r in routers(env):
        role = env[f"{r}_ROLE"]
        st = static_pairs(env, r)
        pool_start, pool_end = pool_bounds(env, r)
        lines += [
            f"  {env[f'{r}_NAME']}:",
            "    os: iosxe",
            "    type: router",
            f"    alias: {r}",
            "    connections:",
            "      defaults:",
            "        via: cli",
            "      cli:",
            "        protocol: ssh",
            "        ip: 127.0.0.1",
            f"        port: {env[f'{r}_SSH']}",
            "        arguments:",
            "          init_exec_commands:",
            "            - terminal length 0",
            "            - terminal width 200",
            "          init_config_commands: []",
            "      console:",
            "        protocol: telnet",
            "        ip: 127.0.0.1",
            f"        port: {env[f'{r}_CONSOLE']}",
            "    custom:",
            f"      role: {role}",
            f"      asn: {env[f'{r}_ASN']}",
            f"      loopback: {env[f'{r}_LOOPBACK']}",
            f"      bgp_prefix: {env[f'{r}_BGP_PREFIX']}",
            f"      lan_ip: {env[f'{r}_LAN_IP']}",
            f"      lan_net: {env[f'{r}_LAN_NET']}",
            f"      nat_net: {env[f'{r}_NAT_NET']}",
            f"      nat_pool: [{pool_start}, {pool_end}]",
            f"      static_first: {st[0][0]}",
            f"      static_last: {st[-1][0]}",
            f"      dynamic_first: {dynamic_addresses(env, r)[0]}",
            f"      dynamic_last: {dynamic_addresses(env, r)[-1]}",
            f"      netconf_port: {env[f'{r}_NETCONF']}",
            f"      restconf_port: {env[f'{r}_RESTCONF']}",
        ]
        if role == "spoke":
            lines += [
                f"      link_local: {env[f'{r}_LINK_LOCAL']}",
                f"      link_hub: {env[f'{r}_LINK_HUB']}",
                f"      tunnel_local: {env[f'{r}_TUNNEL_LOCAL']}",
                f"      tunnel_hub: {env[f'{r}_TUNNEL_HUB']}",
                f"      hub_intf: {env[f'{r}_HUB_INTF']}",
                f"      hub_tunnel: Tunnel{env[f'{r}_HUB_TUNNEL_ID']}",
            ]
        else:
            lines.append(f"      spokes: [{', '.join(spokes(env))}]")

    for h in env["HOSTS"].split():
        r = env[f"{h}_ROUTER"]
        lines += [
            f"  {env[f'{h}_NAME']}:",
            "    os: linux",
            "    type: linux",
            f"    alias: {h}",
            "    credentials:",
            "      default:",
            f"        username: {env['HOST_USER']}",
            f"        password: {env['HOST_PASS']}",
            "    connections:",
            "      cli:",
            "        protocol: ssh",
            "        ip: 127.0.0.1",
            f"        port: {env[f'{h}_SSH']}",
            "    custom:",
            f"      router: {r}",
            f"      ip: {env[f'{h}_IP']}",
            f"      gateway: {env[f'{r}_LAN_IP']}",
            f"      nat_ip: {env[f'{h}_NAT_IP']}",
        ]

    # one entry per device: repeating the hub once per spoke produces a duplicate
    # YAML key and the later block silently wins
    lines += ["", "topology:"]
    hub = env["HUB"]
    lines += [f"  {env[f'{hub}_NAME']}:", "    interfaces:"]
    for r in spokes(env):
        lines += [
            f"      {env[f'{r}_HUB_INTF']}:",
            "        type: ethernet",
            f"        ipv4: {env[f'{r}_LINK_HUB']}/30",
            f"        link: link-{hub.lower()}-{r.lower()}",
        ]
    lines += ["      GigabitEthernet3:", "        type: ethernet",
              f"        ipv4: {env[f'{hub}_LAN_IP']}/24",
              f"        link: lan-{hub.lower()}"]
    for r in spokes(env):
        lines += [
            f"  {env[f'{r}_NAME']}:",
            "    interfaces:",
            "      GigabitEthernet2:",
            "        type: ethernet",
            f"        ipv4: {env[f'{r}_LINK_LOCAL']}/30",
            f"        link: link-{hub.lower()}-{r.lower()}",
            "      GigabitEthernet3:",
            "        type: ethernet",
            f"        ipv4: {env[f'{r}_LAN_IP']}/24",
            f"        link: lan-{r.lower()}",
        ]
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    env = load_env()
    out = sys.argv[1] if len(sys.argv) > 1 else os.path.join(LAB, "testbed", "lab.yaml")
    with open(out, "w") as fh:
        fh.write(render(env))
    print(f"wrote {out}")
